name: Dosu frontend

on:
  pull_request:
    types: [synchronize, opened]

jobs:
  compile-code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Fix the types for linter
        run: yarn fix
      - name: Compile code
        run: yarn tsc --skipLibCheck
      - name: Lint code
        run: yarn lint
